import Search from "./components/Search";
import "./globals.css";
import Link from "next/link";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className='font-mono text-xl p-10'>
				<nav className="w-full px-4 py-3 flex justify-between flex-col md:flex-row gap-4 items-center bg-slate-700">
					<ul className="flex gap-4">
						<li><Link href="/">home</Link></li>
						<li><Link href="/users">users</Link></li>
					</ul>
					<Search />
				</nav>
				{children}
			</body>
		</html>
	);
}
